### ISSUE TITLE
Savsoft quiz 6.0 issues

### ISSUE THREAD

**Issue by prbt2016** [Techkshetra/savsoftquizv6.0#1]
Hello,

I was in the process of manual installation of Savsoft Quiz 6.0 on following environment :

Centos 6.9 Final  with PHP 7.3.28, Apache 2.2 , MYSQL 5.7. 

However i am facing some issues i.e : 

On MYSQL 5.5 and MYSQL 5.6 I get the following error while importing database.sql into the database i.e : 

`1071 - Specified key was too long; max key length is 767 bytes`

However on MYSQL 5.7 after following the following the first six steps as mentioned here : 

https://github.com/Techkshetra/savsoftquizv6.0/blob/main/readme.md

And visiting the link i.e : 

http://YOUR-DOMAINNAME/application/dist/index.html and after entering the default login details i.e : 

username : admin
password : admin

I am not able to log in to the admin panel as it throws an error i.e request timeout. 

Following is the screenshot of the same :

![issue](https://user-images.githubusercontent.com/17871448/132491938-6668b562-0549-4d3a-bf29-2a6d56d0b8cd.jpg)

Could you please replicate this issue at your end?.

**Comment by santoshkumarhiremath** [comment]
Hi,
can you share the installation url or share developer console screenshot (console & network tab) ?
 it seems api_base_url and api_site_url  are incorrect in custom.js file. (step 6)
 
We updated the custom.js file and added debug_mode
download updated /dist/js/custom.js and edit set debug_mode=1;
then clear browser cache and retry.
if api path incorrect then it will show in flash message. if path is correct then check index.php and .htaccess file permission (in api/public folder) 
it should be 0644

**Comment by prbt2016** [comment]
Thanks for the resolution @santoshkumarhiremath . 

After enabling debug with latest custom.js file found out that was due to incorrect api_site_url. 

It's working fine now. 

Just another query, MySQL version 5.1+ is mentioned in docs here  

https://github.com/Techkshetra/savsoftquizv6.0#readme 

but there is an issue on MYSQL 5.5 and 5.6 of 

`1071 - Specified key was too long; max key length is 767 bytes`

while importing the 'database.sql' file in database. The import works fine on MYSQL 5.7.

What is the minimum required MYSQL version for the script ?.

**Comment by santoshkumarhiremath** [comment]
Our team noted the issue with MySql version 5.5 and 5.6 and shortly we will release the update.

**Comment by madhurgupta007** [comment]
I am getting this error while trying to logging in admin dashboard. I am running the savsoft quiz 6.0 code in local host. Can you please help me to resolve this issue ?

Request failed to API url: localhost:8888/api/public/index.php/login/index
Check api and base url path in dist/js/custom.js file. if api application is hosted on different host (domain) then add CORS of application domain. eg. in index.php of api folder add header('Access-Control-Allow-Origin: *');

**Comment by santoshkumarhiremath** [comment]
To fix login login issue read instructions at https://github.com/Techkshetra/savsoftquizv6.0/wiki/First-time-login-troubleshoot
Mysql issue "key was too long" fixed and you can download updated database.sql file
