### ISSUE TITLE
error while trying to logging in admin dashboard

### ISSUE THREAD

**Issue by madhurgupta007** [Techkshetra/savsoftquizv6.0#3]
I am getting this error while trying to logging in admin dashboard. I am running the savsoft quiz 6.0 code in local host. Can you please help me to resolve this issue ?

Request failed to API url: localhost:8888/api/public/index.php/login/index
Check api and base url path in dist/js/custom.js file. if api application is hosted on different host (domain) then add CORS of application domain. eg. in index.php of api folder add header('Access-Control-Allow-Origin: *');

**Comment by namicts** [comment]
I have the same problem. I have tried to check the .htaccess but no clue.

**Comment by franrebo84** [comment]
Hi! I'm in the same situation.  I can add an error that I get in nginx.log:

`myapp_1    | 2022/01/28 18:54:55 [error] 209#209: *3 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 192.168.60.210, server: , request: "POST /api/public/index.php/login/index HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "192.168.11.108", referrer: "http://192.168.11.108/application/dist/index.html"`


Does anyone found a solution for this?

**Comment by santoshkumarhiremath** [comment]
Hi,
Can you share your server environment details? or if possible to share public url so we can check.

**Comment by santoshkumarhiremath** [comment]
read instructions at https://github.com/Techkshetra/savsoftquizv6.0/wiki/First-time-login-troubleshoot and let us know if it fied.

**Comment by franrebo84** [comment]
Hi! thanks for the doc, but Im still stuck at the same place: 

My .env is:
```
  CI_ENVIRONMENT = development

 app.baseURL = 'http://192.168.11.108/'

 database.writeDB.hostname = mariadb
 database.writeDB.database = 'exam'
 database.writeDB.username = 'exam'
 database.writeDB.password = 'exam'
 database.writeDB.DBDriver = MySQLi
 database.readDB.hostname = 'mariadb'
 database.readDB.database = 'exam'
 database.readDB.username = 'exam'
 database.readDB.password = 'exam'
 database.readDB.DBDriver = MySQLi
```


My custom.js vars are:
```
var api_base_url="http://192.168.11.108/api/public/";
var api_site_url="http://192.168.11.108/api/public/index.php/";
```

this is the response of index.php on my broswer:

![image](https://user-images.githubusercontent.com/34930975/151987902-c6cc3081-443b-4563-ba0e-4b5e1305305e.png)

**Comment by namicts** [comment]
I have solved this issue for a month. Actually the main reason I found from my side was the rewrite URL only worked for Apache server (not Nginx). For that reason I had to use an Apache docker as a solution.

**Comment by franrebo84** [comment]
I just saw the very same thing.  I'll try that.
Its ok If PR my dockerfile and docker-compose (once I fixit)?

**Comment by franrebo84** [comment]
Changing to apache made the API work. but now im getting this message from codeigniter:

message: "Unable to connect to the database."

I tested the database connection and it works well, but CodeIgniter still cant connect.

**Comment by namicts** [comment]
@franrebo84 Could I ask if you used 'localhost' or '%' for the database user permission? For me changing to 'localhost' it worked, while '%' it did not.

**Comment by franrebo84** [comment]
I was missing the mysqli extension on my docker image. Now is working like charm!
Things I made to fix it:

- Use apache2 instead of nginx, .htaccess on api/public not work if you use nginx.
- Enable mysqli extension.
- Follow  https://github.com/Techkshetra/savsoftquizv6.0/wiki/First-time-login-troubleshoot for troubleshooting.

Thanks to all!

**Comment by santoshkumarhiremath** [comment]
Thank you for sharing information. Our team will work to fix issue with Nginx serevr.
