### ISSUE TITLE
Inline parameter in SQL query

### ISSUE THREAD

**Issue by Langlais115** [Techkshetra/savsoftquizv6.0#4]
Hi,

I notice that you have some inline parameter in your SQL query.
I just want to notify you, that it is a bad practice as it might be vulnerable to SQL injection.

Try to use prepare statement instead.
Tips:
You might want to have a look at **doctrine** database abstraction layer
It allow you to make prepare statement fairly easily as well as configurable query using query builder.

https://github.com/Techkshetra/savsoftquizv6.0/blob/7a7b10da53ac8c35579ce3ba4b92575e42e587e1/api/app/Controllers/Login.php#L27

**Comment by santoshkumarhiremath** [comment]
Our team noted it and will fix in next release
